name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  


jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Unit Tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: Linting
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build