name: tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'



jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: |
          ls -al
          rm -Rf .yarn/cache
      - run: |
          npm install -g yarn
          yarn install
      - run: yarn test
      - run: yarn lint:cli
      - run: yarn lint:lib
      - name: build package
        shell: bash
        run: |
          set -x
          yarn clean
          yarn node ./build_package.js
          yarn build:cli
          yarn build:lib
