name: tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'



jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Run lint on cli
        run: yarn lint:cli
      - name: Run lint on lib
        run: yarn lint:lib
      - name: Build package
          yarn clean
          yarn build:package
      - name: Build cli tools
        run: yarn build:cli
      - name: Build library
        run: yarn build:lib
